name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build -x test -i --no-daemon -Dspring.profiles.active=prod

      # Docker Image Build and Push
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

        # CD 배포
      - name: Deploy remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.APPCENTER_SERVER_IP}}
          username: ${{secrets.APPCENTER_SERVER_USERNAME}}
          password: ${{secrets.APPCENTER_SERVER_PASSWORD}}
          port: ${{secrets.APPCENTER_SERVER_PORT}}
          script: |
            cd /home/serverking/ingle
            
            # 환경 변수 파일 생성
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # 기존 컨테이너 중지 및 삭제
            if [ "$(docker ps -aq -f name=${{secrets.DOCKER_REPO}})" ]; then
              docker stop ${{secrets.DOCKER_REPO}}
              docker rm ${{secrets.DOCKER_REPO}}
            fi
             # 새 컨테이너 실행
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            docker run -d \
              --name ${{ secrets.DOCKER_REPO }} \
              --env SPRING_PROFILES_ACTIVE=prod \
              --env SPRING_BOOT_JAVA_OPTS="-Duser.timezone=Asia/Seoul" \
              --env-file /home/serverking/ingle/.env \
              -p 8089:8089 \
                ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}